"""
Django settings for google_auth project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", None)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    'rest_framework_simplejwt',
    'rest_framework',
    'rest_framework.authtoken',
]

LOCAL_APPS = [
    'google_api',
    'github_api',
    'linkedin_api',
    'facebook_api',
]

INSTALLED_APPS += THIRD_PARTY_APPS
INSTALLED_APPS += LOCAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "google_auth.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "google_auth.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY", None)
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET", None)
SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI", None)
SOCIAL_AUTH_GOOGLE_CLIENT_SECRET_FILE = os.getenv("SOCIAL_AUTH_GOOGLE_CLIENT_SECRET_FILE", None)
SOCIAL_AUTH_GOOGLE_OAUTH2_EXTRA_DATA = ['email']


SOCIAL_AUTH_GITHUB_CLIENT_ID = os.getenv("SOCIAL_AUTH_GITHUB_CLIENT_ID", None)
SOCIAL_AUTH_GITHUB_CLIENT_SECRET = os.getenv("SOCIAL_AUTH_GITHUB_CLIENT_SECRET", None)
SOCIAL_AUTH_GITHUB_REDIRECT_URI = os.getenv("SOCIAL_AUTH_GITHUB_REDIRECT_URI", None)
SOCIAL_AUTH_GITHUB_STATE = os.getenv("SOCIAL_AUTH_GITHUB_STATE", None)
SOCIAL_AUTH_GITHUB_ACCESS_TOKEN_URL = os.getenv("SOCIAL_AUTH_GITHUB_ACCESS_TOKEN_URL", None)
SOCIAL_AUTH_GITHUB_USER_INFO_URL = os.getenv("SOCIAL_AUTH_GITHUB_USER_INFO_URL", None)


SOCIAL_AUTH_LINKEDIN_CLIENT_ID = os.getenv("SOCIAL_AUTH_LINKEDIN_CLIENT_ID", None)
SOCIAL_AUTH_LINKEDIN_CLIENT_SECRET = os.getenv("SOCIAL_AUTH_LINKEDIN_CLIENT_SECRET", None)
SOCIAL_AUTH_LINKEDIN_REDIRECT_URI = os.getenv("SOCIAL_AUTH_LINKEDIN_REDIRECT_URI", None)
SOCIAL_AUTH_LINKEDIN_ACCESS_TOKEN_URL = os.getenv("SOCIAL_AUTH_LINKEDIN_ACCESS_TOKEN_URL", None)
SOCIAL_AUTH_LINKEDIN_USER_INFO_URL = os.getenv("SOCIAL_AUTH_LINKEDIN_USER_INFO_URL", None)


SOCIAL_AUTH_FACEBOOK_APP_ID = os.getenv("SOCIAL_AUTH_FACEBOOK_APP_ID", None)
SOCIAL_AUTH_FACEBOOK_APP_SECRET = os.getenv("SOCIAL_AUTH_FACEBOOK_APP_SECRET", None)
SOCIAL_AUTH_FACEBOOK_REDIRECT_URI = os.getenv("SOCIAL_AUTH_FACEBOOK_REDIRECT_URI", None)
SOCIAL_AUTH_FACEBOOK_ACCESS_TOKEN_URL = os.getenv("SOCIAL_AUTH_FACEBOOK_ACCESS_TOKEN_URL", None)
SOCIAL_AUTH_FACEBOOK_USER_INFO_URL = os.getenv("SOCIAL_AUTH_FACEBOOK_USER_INFO_URL", None)

AUTH_USER_MODEL = 'google_api.User'
