# Generated by Django 5.1.7 on 2025-03-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("google_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
